import type { Report } from "@/types/report";
import { analyzeReport, generateBlockchainTx } from "@/lib/ai";

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

function num(n: number) {
  return `S${String(n).padStart(3, "0")}`;
}

const NOW = Date.now();

export const SEED_REPORTS: Report[] = [
  {
    id: "seed_r1",
    number: num(247),
    category: "routes",
    description:
      "Énorme nid de poule au carrefour, un taxi a déjà eu un accident hier soir, c'est devenu très dangereux.",
    photoUris: [],
    quartier: "Cocody",
    address: "Rue des Jardins, près du carrefour Saint-Jean",
    latitude: 5.359,
    longitude: -3.989,
    createdAt: NOW - 6 * HOUR,
    authorPseudo: "Aïssata K.",
    isAnonymous: false,
    status: "en_cours",
    history: [
      { status: "soumis", at: NOW - 6 * HOUR },
      { status: "valide", at: NOW - 5 * HOUR, note: "Vérifié par la mairie" },
      {
        status: "en_cours",
        at: NOW - 2 * HOUR,
        note: "Équipe de voirie dépêchée",
      },
    ],
    ai: analyzeReport({
      description: "Énorme nid de poule, accident, dangereux",
      category: "routes",
      quartier: "Cocody",
      hasPhoto: true,
      similarCount: 7,
    }),
    blockchain: generateBlockchainTx(),
    upvotes: 23,
    isMine: false,
  },
  {
    id: "seed_r2",
    number: num(246),
    category: "eclairage",
    description:
      "Tous les lampadaires de la rue sont éteints depuis 4 jours, on n'y voit rien la nuit.",
    photoUris: [],
    quartier: "Yopougon",
    address: "Rue Princesse, secteur Niangon",
    latitude: 5.337,
    longitude: -4.082,
    createdAt: NOW - 2 * DAY,
    authorPseudo: "Moussa T.",
    isAnonymous: false,
    status: "valide",
    history: [
      { status: "soumis", at: NOW - 2 * DAY },
      { status: "valide", at: NOW - 1 * DAY, note: "CIE notifiée" },
    ],
    ai: analyzeReport({
      description: "Lampadaires éteints depuis 4 jours",
      category: "eclairage",
      quartier: "Yopougon",
      hasPhoto: false,
      similarCount: 3,
    }),
    blockchain: generateBlockchainTx(),
    upvotes: 14,
    isMine: false,
  },
  {
    id: "seed_r3",
    number: num(245),
    category: "eau",
    description:
      "Fuite d'eau importante sur la conduite principale, l'eau coule sans arrêt depuis ce matin.",
    photoUris: [],
    quartier: "Plateau",
    address: "Boulevard de la République",
    latitude: 5.32,
    longitude: -4.022,
    createdAt: NOW - 8 * HOUR,
    authorPseudo: "Yao B.",
    isAnonymous: false,
    status: "soumis",
    history: [{ status: "soumis", at: NOW - 8 * HOUR }],
    ai: analyzeReport({
      description: "Fuite d'eau importante, urgent",
      category: "eau",
      quartier: "Plateau",
      hasPhoto: true,
      similarCount: 2,
    }),
    blockchain: generateBlockchainTx(),
    upvotes: 8,
    isMine: false,
  },
  {
    id: "seed_r4",
    number: num(244),
    category: "dechets",
    description:
      "Ordures jamais ramassées depuis deux semaines, l'odeur est insupportable et attire les rats.",
    photoUris: [],
    quartier: "Adjamé",
    address: "Marché Gouro, allée 3",
    latitude: 5.359,
    longitude: -4.026,
    createdAt: NOW - 5 * DAY,
    authorPseudo: "Fatou D.",
    isAnonymous: false,
    status: "resolu",
    history: [
      { status: "soumis", at: NOW - 5 * DAY },
      { status: "valide", at: NOW - 4 * DAY },
      { status: "en_cours", at: NOW - 3 * DAY },
      { status: "resolu", at: NOW - 1 * DAY, note: "Collecte effectuée" },
    ],
    ai: analyzeReport({
      description: "Ordures pas ramassées, odeur, rats",
      category: "dechets",
      quartier: "Adjamé",
      hasPhoto: true,
      similarCount: 12,
    }),
    blockchain: generateBlockchainTx(),
    upvotes: 41,
    isMine: false,
  },
  {
    id: "seed_r5",
    number: num(243),
    category: "ecoles",
    description:
      "Le mur de l'école primaire menace de s'effondrer sur la cour de récréation des enfants.",
    photoUris: [],
    quartier: "Abobo",
    address: "EPP Abobo Sagbé",
    latitude: 5.428,
    longitude: -4.046,
    createdAt: NOW - 12 * HOUR,
    authorPseudo: "Kouadio N.",
    isAnonymous: false,
    status: "valide",
    history: [
      { status: "soumis", at: NOW - 12 * HOUR },
      { status: "valide", at: NOW - 10 * HOUR, note: "Inspection programmée" },
    ],
    ai: analyzeReport({
      description: "Mur école effondré danger enfants",
      category: "ecoles",
      quartier: "Abobo",
      hasPhoto: true,
      similarCount: 0,
    }),
    blockchain: generateBlockchainTx(),
    upvotes: 67,
    isMine: false,
  },
  {
    id: "seed_r6",
    number: num(242),
    category: "securite",
    description:
      "Câble électrique dénudé qui pend au-dessus du trottoir, risque d'électrocution.",
    photoUris: [],
    quartier: "Treichville",
    address: "Avenue 16, Rue 22",
    latitude: 5.296,
    longitude: -4.0,
    createdAt: NOW - 3 * HOUR,
    authorPseudo: "Citoyen anonyme",
    isAnonymous: true,
    status: "soumis",
    history: [{ status: "soumis", at: NOW - 3 * HOUR }],
    ai: analyzeReport({
      description: "Câble électrique dénudé, électrocution, danger",
      category: "securite",
      quartier: "Treichville",
      hasPhoto: false,
      similarCount: 0,
    }),
    blockchain: generateBlockchainTx(),
    upvotes: 5,
    isMine: false,
  },
  {
    id: "seed_r7",
    number: num(241),
    category: "routes",
    description:
      "Plusieurs trous sur la chaussée, les voitures roulent en zigzag pour les éviter.",
    photoUris: [],
    quartier: "Marcory",
    address: "Boulevard du Gabon",
    latitude: 5.288,
    longitude: -3.989,
    createdAt: NOW - 30 * HOUR,
    authorPseudo: "Sékou L.",
    isAnonymous: false,
    status: "en_cours",
    history: [
      { status: "soumis", at: NOW - 30 * HOUR },
      { status: "valide", at: NOW - 26 * HOUR },
      { status: "en_cours", at: NOW - 10 * HOUR },
    ],
    ai: analyzeReport({
      description: "Trous chaussée voitures zigzag",
      category: "routes",
      quartier: "Marcory",
      hasPhoto: true,
      similarCount: 4,
    }),
    blockchain: generateBlockchainTx(),
    upvotes: 18,
    isMine: false,
  },
  {
    id: "seed_r8",
    number: num(240),
    category: "eclairage",
    description: "Lampadaire grillé devant l'école.",
    photoUris: [],
    quartier: "Cocody",
    address: "Rue des Jasmins",
    latitude: 5.362,
    longitude: -3.985,
    createdAt: NOW - 4 * DAY,
    authorPseudo: "Marie A.",
    isAnonymous: false,
    status: "resolu",
    history: [
      { status: "soumis", at: NOW - 4 * DAY },
      { status: "valide", at: NOW - 3 * DAY },
      { status: "en_cours", at: NOW - 2 * DAY },
      { status: "resolu", at: NOW - 12 * HOUR },
    ],
    ai: analyzeReport({
      description: "Lampadaire grillé école",
      category: "eclairage",
      quartier: "Cocody",
      hasPhoto: false,
      similarCount: 1,
    }),
    blockchain: generateBlockchainTx(),
    upvotes: 9,
    isMine: false,
  },
];
