kind = "mobile"
previewPath = "/"
title = "SentinelleCI"
version = "1.0.0"
id = "artifacts/sentinelle-ci"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19802

[services.development]
run = "pnpm --filter @workspace/sentinelle-ci run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sentinelle-ci", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/sentinelle-ci", "run", "serve" ]

[services.env]
PORT = "19802"
BASE_PATH = "/"
